# action.yml
name: "Sqitch Deployment"
description: "Deploy schema in GHA wth sqitch"
inputs:
  directory:
    description: "Directory of schema"
    required: true
  host:
    description: "Database host"
    required: true
  port:
    description: "Database Port"
    required: true
    default: "5432"
  additional_sqitch_args:
    description: "Additional sqitch arguments"
    required: false
  password:
    description: "Database Password"
    required: true
  user:
    description: "Database User"
    required: true
  skip-snapshooter:
    description: "Skip snapshooter setup"
    required: true
    default: "true"
  application-user:
    description: "Application Database User"
    required: true
  database:
    description: "Database Name"
    required: true
  ssl-mode:
    description: "Database Name"
    required: true
    default: "required"
outputs:
  time: # id of output
    description: "The time you deployed the schema"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.user }}
    - ${{ inputs.password }}
    - ${{ inputs.database }}
    - ${{ inputs.host }}
    - ${{ inputs.port }}
    - ${{ inputs.ssl-mode }}
    - ${{ inputs.directory }}
    - ${{ inputs.additional_sqitch_args }}
    - ${{ inputs.application-user }}
    - ${{ inputs.skip-snapshooter }}
